### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by egabancho** [rtv/Stage#5]
on Mac OS 10.6.6, compiling rtv-Stage-508538b I got this error:

[ 98%] Building CXX object libstageplugin/CMakeFiles/stageplugin.dir/p_graphics.o
/rtv-Stage-508538b/libstageplugin/p_graphics.cc: In member function ‘virtual int InterfaceGraphics2d::ProcessMessage(QueuePointer&, player_msghdr_t_, void_)’:
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:236: error: ‘PLAYER_GRAPHICS2D_CMD_MULTILINE’ was not declared in this scope
/rtv-Stage-508538b/libstageplugin/p_graphics.cc: In member function ‘virtual void PlayerGraphics2dVis::RenderItem(Message&)’:
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:277: error: ‘PLAYER_GRAPHICS2D_CMD_MULTILINE’ was not declared in this scope
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:278: error: ‘player_graphics2d_cmd_multiline_t’ was not declared in this scope
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:279: error: ‘data’ was not declared in this scope
s/rtv-Stage-508538b/libstageplugin/p_graphics.cc:280: error: expected type-specifier before ‘player_graphics2d_cmd_multiline_t’
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:280: error: expected `>' before ‘player_graphics2d_cmd_multiline_t’
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:280: error: expected`(' before ‘player_graphics2d_cmd_multiline_t’
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:280: error: expected primary-expression before ‘>’ token
/rtv-Stage-508538b/libstageplugin/p_graphics.cc:280: error: expected `)' before ‘;’ token
make[2]: **\* [libstageplugin/CMakeFiles/stageplugin.dir/p_graphics.o] Error 1
make[1]: **\* [libstageplugin/CMakeFiles/stageplugin.dir/all] Error 2
make: **\* [all] Error 2

I'm getting the same compiling error if I work with Stage-4.0.0 or the latest version cloned with git. But Stage 3.2.2 works fine for me.
